version: '3.9'

services:
  market:
    image: market-app
    container_name: market-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.bin/:/root/
      - ./configs/:/root/configs/
    env_file:
      - .env
    ports:
      - 8080:8080

  postgres:
    restart: always
    image: postgres:latest
    container_name: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./schema/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_PASSWORD: "qwerty"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "marketDb"
    ports:
      - 5436:5432