postgres:
  dbname: marketDb
  sslmode: disable

http:
  port: 8080
  readTimeout: 10s
  writeTimeout: 10s
  maxHeaderMegaBytes: 1

auth:
  accessTokenTTL: 12h

hash:
  memoryMegaBytes: 1
  iterations: 3
  parallelism: 2
  saltLength: 16
  keyLength: 32
